(function() {var implementors = {};
implementors['encryptfile'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='encryptfile/enum.Mode.html' title='encryptfile::Mode'>Mode</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='encryptfile/enum.OutputOption.html' title='encryptfile::OutputOption'>OutputOption</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='encryptfile/enum.InputStream.html' title='encryptfile::InputStream'>InputStream</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='encryptfile/enum.OutputStream.html' title='encryptfile::OutputStream'>OutputStream</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='encryptfile/enum.RngMode.html' title='encryptfile::RngMode'>RngMode</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='encryptfile/enum.InitializationVector.html' title='encryptfile::InitializationVector'>InitializationVector</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='encryptfile/struct.ScryptLogN.html' title='encryptfile::ScryptLogN'>ScryptLogN</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='encryptfile/struct.ScryptR.html' title='encryptfile::ScryptR'>ScryptR</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='encryptfile/struct.ScryptP.html' title='encryptfile::ScryptP'>ScryptP</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='encryptfile/enum.PasswordKeyGenMethod.html' title='encryptfile::PasswordKeyGenMethod'>PasswordKeyGenMethod</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='encryptfile/enum.PasswordType.html' title='encryptfile::PasswordType'>PasswordType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='encryptfile/struct.Config.html' title='encryptfile::Config'>Config</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
